openapi: 3.2.0
info:
  title: Administrative Office of the U.S. Courts PACER Case Locator Parties API
  description: API for searching federal court cases and associated parties.
  version: 1.0.0
servers:
- url: https://qa-pcl.uscourts.gov/pcl-public-api/rest
  description: QA Environment
- url: https://pcl.uscourts.gov/pcl-public-api/rest
  description: Production Environment
tags:
- name: Parties
paths:
  /parties/find:
    post:
      summary: Administrative Office of the U.S. Courts Search for parties
      description: Returns a list of parties matching the search criteria.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartySearchRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartySearchResponse'
      tags:
      - Parties
components:
  schemas:
    PartySearchResponse:
      type: object
      properties:
        receipt:
          type: object
          properties:
            transactionDate:
              type: string
              format: date-time
            billablePages:
              type: integer
            searchFee:
              type: string
        parties:
          type: array
          items:
            type: object
            properties:
              lastName:
                type: string
              firstName:
                type: string
              caseNumberFull:
                type: string
    PartySearchRequest:
      type: object
      properties:
        lastName:
          type: string
        firstName:
          type: string
        caseNumberFull:
          type: string
